### ISSUE TITLE
Fix the permalink issue affecting child pages of Services

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/sfwdtheme#18]
Trying to go to any sub page os Services results in a 404.

**Comment by michaeltorbert** [comment]
Strangely, this works on my dev site.

**Comment by michaeltorbert** [comment]
Ok so the reason it's breaking is that the parent page has the slug of "services" and we have a taxonomy for portfolio also called "services". I have no idea why it works on my local dev site. (On sfwddev.internal, if you change the slug of the parent page from "sevices" to "service2" it works.) 

Either a) I can come up with some hack to make it work or b) one of them can be changed. If one existed before and the other is new, I recommend changing the new one so we can keep as many of our URLs the same as possible... 
@wpsmort What are your thoughts?

**Comment by michaeltorbert** [comment]
Ok so on my local site, it's the terms inside the "services" taxonomy that don't work. It's weirdly flipped from sfwddev.internal.

**Comment by wpsmort** [comment]
@michaeltorbert I think we should change the slug of the custom taxonomy as it's better SEO to have the Services sub pages have the parent page slug in the URL.

**Comment by wpsmort** [comment]
This is done,
