### ISSUE TITLE
Test HTTPS and fix issues with insecure content

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/sfwdtheme#23]
Go through each page and fix any issues with insecure content.

**Comment by michaeltorbert** [comment]
We should be able to search for http:

for files, just use grep or finder
for posts, just use search in the list of all posts screen (needs to be done for each post type)

**Comment by wpsmort** [comment]
This is done.  I've verified there are no instances of http:// in the child theme code or in the content. 

I've opened an issue for some instances of HTTP in the sfwdplugin here https://github.com/semperfiwebdesign/sfwdplugin/issues/11
