### ISSUE TITLE
themecheck the new theme

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/sfwdtheme#27]
wordpress.org/plugins/theme-check/
themecheck.org/

We should use both of these as one is a fork of the other.

**Comment by wpsmort** [comment]
I have run the Theme Check plugin against the child theme.  Here are the issues it found along with my notes:

WARNING: More than one text-domain is being used in this theme. This means the theme will not be compatible with WordPress.org language packs.  The domains found are responsive, tgmpa.

- I have grepped the theme files and cannot find any reference to tgmpa in any file.

WARNING: Your theme appears to be in the wrong directory for the theme name. The directory name must match the slug of the theme. This theme's correct slug and text-domain is sfwd-theme.
(If this is a child theme, you can ignore this error.)

- I'm not sure we can change this as it's tied to Github.

WARNING: Found pub-2109598555501885 in the file fonts/MyriadPro-Regular.otf. Google advertising code detected.
Line 1276: data-ad-client='ca-pub-2109598555501885'
Line 1400: data-ad-client='ca-pub-2109598555501885'
Line 1470: data-ad-client='ca-pub-2109598555501885'

- PR #41 removes this font as we're not using it.

WARNING: Found pub-2109598555501885 in the file fonts/AkzidenzGroteskBE-Bold.otf. Google advertising code detected.
Line 812: google_ad_client = 'ca-pub-2109598555501885';
Line 890: google_ad_client = 'ca-pub-2109598555501885';
Line 965: google_ad_client = 'ca-pub-2109598555501885';

- PR #41 replaces this font with Helvetica which looks just the same and is a standard font.

REQUIRED: Your Theme URI and Author URI should not be the same.

- PR #41 changes the Author URI.

**Comment by wpsmort** [comment]
In addition to the items above, the Theme Check also found 12 items where a translation function is missing a text-domain.  @michaeltorbert Is this something want to fix or can these be ignored?

**Comment by michaeltorbert** [comment]
@wpsmort We make an issue if you think there's any change we'd upload this to .org. Otherwise I'd ignore it.
