### ISSUE TITLE
Style the call to action on the changelog page

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/sfwdtheme#32]
From https://github.com/semperfiwebdesign/semperpluginstore/issues/475

Improve the appearance of the upsell call to action here - https://semperfiwebdesign.com/all-in-one-seo-pack-release-history/

**Comment by wpsmort** [comment]
This is done in the page content.

**Comment by michaeltorbert** [comment]
I think this page still has areas for improvement.

<img width="349" alt="screen shot 2019-02-18 at 2 08 42 pm" src="https://user-images.githubusercontent.com/17364998/52971833-ead56a80-3386-11e9-8645-e85ba25bd7ce.png">

**Comment by wpsmort** [comment]
This button styling is fixed in PR #38.
