### ISSUE TITLE
Add government contractor logo/message

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/sfwdtheme#33]
See also https://github.com/semperfiwebdesign/semperpluginstheme/issues/105

**Comment by wpsmort** [comment]
I have added the logo to our About page here - https://semperfiwebdesign.com/about/

**Comment by wpsmort** [comment]
@michaeltorbert Would you like me to also add the logo to the footer of the site or is the About page fine?

**Comment by michaeltorbert** [comment]
@dawatorbert can answer this better than I can.

**Comment by dawatorbert** [comment]
I think About page is fine @wpsmort
